Missing command for building the UI in the Readme
aws-samples/websocket-chat-application pull request #6
Opened 2022-09-01 20:03 UTC by greenchapeljohn

The top-level Readme has a missing command for building the UI 
User must run npm i ( npm install) first.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-09-02 10:08 UTC, santatamas commented on infrastructure/lib/frontend-stack.ts
> +        domainPrefix: "new-serverless-chat-users" // TODO: extract to stack parameter
I'd leave this unchanged for now. Adding new won't solve the problem that this is hardcoded. My plan is to move this to a stack-level parameter.

2022-09-02 10:14 UTC, santatamas requested changes
Please re-add the 2 deleted files (package-lock.json & test-auth-stack.ts), as they should stay in the repository.

I also left comments in the other files.

2022-09-02 10:14 UTC, santatamas commented on infrastructure/lib/frontend-stack.ts
> +        domainPrefix: "new-serverless-chat-users" // TODO: extract to stack parameter
Please remove the "new" prefix, as it doesn't add anything of value. The plan is to move this to a stack-level parameter.

2022-09-02 10:14 UTC, santatamas commented on infrastructure/package.json
> +    "@aws-cdk/aws-apigatewayv2-alpha": "^2.40.0-alpha.0",
What's the purpose of adding this dependency? I might have missed it before.

2022-09-02 10:23 UTC, greenchapeljohn commented on infrastructure/package.json
> +    "@aws-cdk/aws-apigatewayv2-alpha": "^2.40.0-alpha.0",
Oops, forgot to change back to my fork. The changes in this last commit was what I needed to get the whole project to build and run.

2022-09-02 11:10 UTC, greenchapeljohn commented
Well that was a bit messy as I only ment to commit the first commit and the others back to my local fork. 
I have added the domainPrefix as a stack prop as the TODO mentioned.

2022-09-02 11:20 UTC, greenchapeljohn commented on infrastructure/lib/frontend-stack.ts
> +        domainPrefix: "new-serverless-chat-users" // TODO: extract to stack parameter
The reason I had to make this change is that if the domain is not changed it throws the following error.

Domain already associated with another user pool. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException;

2022-09-02 12:33 UTC, santatamas commented on infrastructure/package.json
> +    "@aws-cdk/aws-apigatewayv2-alpha": "^2.40.0-alpha.0",
I see. I had no problem compiling the infrastructure project without this dependency. Please remove this file from the PR and if you still find that you can't compile the project with the current references, submit a new one with the dependency updates only. Please also make sure that you match the package versions across the project to avoid incompatibilities. e.g. if the rest of the packages have 2.29.1-alpha.0, match your new dependency with the same version (if available). Thanks!

2022-09-02 12:34 UTC, santatamas commented on infrastructure/lib/frontend-stack.ts
> +        domainPrefix: "new-serverless-chat-users" // TODO: extract to stack parameter
That's fair, this domain name should be customised for your deployment only. I'll add that section to the readme as I see how that can cause confusion!

2022-09-02 12:37 UTC, santatamas commented on infrastructure/package.json
> +    "@aws-cdk/aws-apigatewayv2-alpha": "^2.40.0-alpha.0",
In any case, since the pull request should be about the readme change (as the title suggest), in the future it's a good practice to submit multiple narrow-focused PRs. Otherwise it's a bit tricky to review the changes. Thanks a lot for your contribution! It's truly appreciated :)

2022-09-02 12:49 UTC, greenchapeljohn commented on infrastructure/package.json
> +    "@aws-cdk/aws-apigatewayv2-alpha": "^2.40.0-alpha.0",
Its ok, it was supposed to just be a Readme contribution
I can remove the dependency ( and open another PR as I planned originally  )

2022-09-02 13:07 UTC, greenchapeljohn commented on infrastructure/package.json
> +    "@aws-cdk/aws-apigatewayv2-alpha": "^2.40.0-alpha.0",
Looks like you beat me to it

2022-09-07 09:38 UTC, santatamas commented
> Well that was a bit messy as I only ment to commit the first commit and the others back to my local fork. I have added the domainPrefix as a stack prop as the TODO mentioned.

Thanks, I can still see the ""@aws-cdk/aws-apigatewayv2-alpha": "^2.40.0-alpha.0"," in package-lock.json though. Please remove this file from the PR as well.

2022-09-08 09:42 UTC, santatamas approved these changes

2022-09-08 10:09 UTC, merged

2022-09-08 10:09 UTC, santatamas commented
Thanks for all your effort!